apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    meta.helm.sh/release-name: crypto-exchange
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2025-11-07T15:02:05Z"
  generation: 2
  labels:
    app.kubernetes.io/instance: crypto-exchange
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: crypto-exchange
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: crypto-exchange-0.1.0
  name: crypto-exchange
  namespace: default
  resourceVersion: "27765"
  uid: b5de20f6-0d12-48ac-a44e-ad46fbfa404f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: crypto-exchange
      app.kubernetes.io/name: crypto-exchange
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: crypto-exchange
        app.kubernetes.io/name: crypto-exchange
    spec:
      containers:
      - args:
        - --bind
        - 0.0.0.0:8000
        - CryptoCurrencyExchange.wsgi
        command:
        - gunicorn
        env:
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: djangoSecretKey
              name: crypto-exchange-secrets
        - name: DATABASE_URL
          value: postgres://crypto_user:$(DB_PASSWORD)@postgresql:5432/crypto_db
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: dbPassword
              name: crypto-exchange-secrets
        - name: DJANGO_ALLOWED_HOSTS
          value: crypto.minikube,localhost,127.0.0.1
        image: crypto-exchange:local-dev
        imagePullPolicy: Never
        name: crypto-exchange
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-11-07T15:02:05Z"
    lastUpdateTime: "2025-11-07T16:44:53Z"
    message: ReplicaSet "crypto-exchange-7d54fc98d7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-11-07T18:18:54Z"
    lastUpdateTime: "2025-11-07T18:18:54Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
