apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: crypto-exchange
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2025-11-07T15:02:05Z"
  labels:
    app.kubernetes.io/instance: crypto-exchange
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: crypto-exchange
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: crypto-exchange-0.1.0
  name: crypto-exchange
  namespace: default
  resourceVersion: "17927"
  uid: a69fd415-336e-4e24-88b7-088a96a5677e
spec:
  clusterIP: 10.108.239.156
  clusterIPs:
  - 10.108.239.156
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: crypto-exchange
    app.kubernetes.io/name: crypto-exchange
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
