apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "crypto-exchange.fullname" . }}
  labels:
    # Tell Prometheus Operator to use this
    release: prometheus
spec:
  selector:
    matchLabels:
      app: crypto-exchange  # <-- Matches the label we added to our Service
  endpoints:
  - port: http            # <-- Matches the 'name' of the port in our Service
    path: /metrics        # <-- The URL path we just added
    interval: 15s
  namespaceSelector:
    matchNames:
    - default