---
# Source: crypto-exchange/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-crypto-exchange-secrets
type: Opaque
data:
  djangoSecretKey: "V3l5NFp3c01MVy1Vb2MtZk1KTExURmlzbkpqN2dNOFpXcDBka3lTczF4MUhscEpwdklBaENFbGF4TTdwTzhIWElsVQ=="
  dbPassword: "UEBzc3cwcmQxMjMl"
---
# Source: crypto-exchange/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-crypto-exchange
  labels:
    helm.sh/chart: crypto-exchange-0.1.0
    app.kubernetes.io/name: crypto-exchange
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: crypto-exchange
    app.kubernetes.io/instance: release-name
---
# Source: crypto-exchange/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  # This name must match what you put in 'database.host' in values.yaml
  name: postgres
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  # This selector must match the labels in your StatefulSet
  selector:
    app: postgres
---
# Source: crypto-exchange/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-crypto-exchange
  labels:
    helm.sh/chart: crypto-exchange-0.1.0
    app.kubernetes.io/name: crypto-exchange
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: crypto-exchange
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: crypto-exchange
        app.kubernetes.io/instance: release-name
    spec:
      containers:
        - name: crypto-exchange
          image: "shararehsadri/crypto-exchange:0.0.1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          command: ["gunicorn"]
          args:
            - "--bind"
            - "0.0.0.0:8000"
            - "CryptoCurrencyExchange.wsgi"
          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: release-name-crypto-exchange-secrets
                  key: djangoSecretKey
            - name: DATABASE_URL
              value: "postgres://crypto_user:$(DB_PASSWORD)@postgres:5432/crypto_db"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: release-name-crypto-exchange-secrets
                  key: dbPassword
            - name: DJANGO_ALLOWED_HOSTS
              # Using a template function to ensure this line is parsed correctly
              value: crypto.example.com,localhost,127.0.0.1
---
# Source: crypto-exchange/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres-headless
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: "postgres:15-alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgresql
          env:
            - name: POSTGRES_USER
              value: crypto_user
            - name: POSTGRES_PASSWORD
              value: SUPER_SECRET_PASSWORD
            - name: POSTGRES_DB
              value: crypto_db
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
---
# Source: crypto-exchange/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-name-crypto-exchange
  labels:
    helm.sh/chart: crypto-exchange-0.1.0
    app.kubernetes.io/name: crypto-exchange
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  ingressClassName: nginx
  rules:
    - host: "crypto.example.com"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: release-name-crypto-exchange
                port:
                  number: 8000
